name: MinecartAnnouncer
version: '3.2'
main: com.gregorune.minecartannoucer.MinecartAnnouncer
api-version: '26.2'
commands:
  announcer:
    description: 'Get information about plugin'
    usage: 'announcer <subcommand>'

permissions:
  mcannouncer.dev:
    description: 'Allows usage of developer commands for debugging'
    default: false
  mcannouncer.get_messages:
    description: 'Allows player to see messages, I dont know why you would need that setting but sure'
    default: true
  mcannouncer.edit_messages:
    description: 'Allows adding and removing announcement messages'
    default: true